- name: Install MySQL
  apt:
    name: mysql-server
    state: present

- name: Start MySQL
  service:
    name: mysql
    state: started
    enabled: yes

- name: Create Database
  mysql_db:
    name: mydb
    state: present

- name: Create User
  mysql_user:
    name: myuser
    password: mypassword
    priv: 'mydb.*:ALL'
    host: '%'
    state: present

- name: Install pymysql
  apt:
    name: python3-pymysql
    state: present